defmodule AshHarness.ToolGen.SkillModule do
  @moduledoc """
  Compile-time emitter for a per-resource `Skill` helper. The emitted
  module exposes a `skill/1` function that takes an optional agent
  override and returns a `%Jido.Composer.Skill{}` whose `tools` list
  is the per-action modules generated by
  `AshHarness.ToolGen.ActionModule`.
  """

  alias AshHarness.ToolGen

  @doc """
  Returns the AST that defines the skill module for a given resource.
  Embedded in the agent's DSL state via `Transformer.eval/3`.
  """
  @spec quoted(module(), module(), [module()]) :: Macro.t()
  def quoted(agent_module, resource_module, action_modules) do
    skill_mod = ToolGen.skill_module(agent_module, resource_module)
    name = AshHarness.Schema.resource_short_name(resource_module)

    quote do
      defmodule unquote(skill_mod) do
        @moduledoc false

        @agent unquote(agent_module)
        @resource unquote(resource_module)
        @tools unquote(action_modules)
        @name unquote(name)

        @doc false
        def __agent__, do: @agent
        @doc false
        def __resource__, do: @resource
        @doc false
        def tool_modules, do: @tools

        @doc """
        Build a `%Jido.Composer.Skill{}` for this resource.
        """
        def skill(opts \\ []) do
          actor = Keyword.get(opts, :actor)

          %Jido.Composer.Skill{
            name: @name,
            description: AshHarness.Resource.Info.description(@resource) || inspect(@resource),
            prompt_fragment: AshHarness.ContextRenderer.render_resource(@agent, @resource, actor),
            tools: @tools
          }
        end
      end
    end
  end
end
