defmodule AshHarness.Harness.OrchestratorFactory do
  @moduledoc """
  Builds the runtime orchestrator agent for a session.

  Each agent module that `use AshHarness.Agent` has a sibling
  orchestrator module generated by
  `AshHarness.ToolGen.OrchestratorModule` — for example,
  `MyApp.TriageAgent` produces
  `AshHarness.Generated.MyApp.TriageAgent.Orchestrator`. The factory
  calls that module's `new/0` and then `configure/2` to inject the
  scoped tool nodes (with `requires_approval: true` for
  `confirm_before` actions), the rendered system prompt, and any
  per-session overrides like `:req_options`.

  Skill modules (`<MyAgent>.Skills.<Resource>`) keep working for
  `AshHarness.Tool.dynamic/2` and any host application that wants to
  assemble agents at runtime from skill lists.
  """

  alias AshHarness.Agent.Info, as: AgentInfo
  alias AshHarness.Harness.Session
  alias AshHarness.ToolGen.OrchestratorModule
  alias Jido.Agent.Strategy.State, as: StratState
  alias Jido.Composer.Skill

  @doc """
  Build a Jido orchestrator agent for the session. Returns
  `{:ok, agent}` or `{:error, reason}`.
  """
  @spec build(Session.t()) :: {:ok, term()} | {:error, term()}
  def build(%Session{agent: agent_module} = session) do
    orch_mod = OrchestratorModule.orchestrator_module(agent_module)

    if Code.ensure_loaded?(orch_mod) and function_exported?(orch_mod, :new, 0) do
      build_with_generated_orchestrator(orch_mod, session)
    else
      build_with_skill_assemble(session)
    end
  end

  defp build_with_generated_orchestrator(orch_mod, %Session{} = session) do
    agent = orch_mod.new()
    nodes = orch_mod.tool_nodes()

    overrides =
      [
        nodes: nodes,
        system_prompt: base_prompt(session)
      ]
      |> maybe_put(:model, session.model)
      |> Keyword.merge(extra_opts(session))

    configured = orch_mod.configure(agent, overrides)
    {:ok, apply_approval_gates(configured, nodes)}
  rescue
    e -> {:error, e}
  end

  defp apply_approval_gates(agent, nodes) do
    gated_names =
      nodes
      |> Enum.filter(fn
        {mod, opts} when is_atom(mod) and is_list(opts) ->
          Keyword.get(opts, :requires_approval, false)

        _ ->
          false
      end)
      |> Enum.map(fn {mod, _opts} -> node_name(mod) end)

    StratState.update(agent, fn
      %{approval_gate: nil} = s ->
        s

      %{approval_gate: ag} = s ->
        %{s | approval_gate: %{ag | gated_node_names: MapSet.new(gated_names)}}

      s ->
        s
    end)
  end

  defp node_name(mod) do
    Code.ensure_loaded!(mod)

    if function_exported?(mod, :name, 0) do
      mod.name()
    else
      mod |> Module.split() |> List.last() |> Macro.underscore()
    end
  end

  defp build_with_skill_assemble(%Session{} = session) do
    skills = build_skills(session)
    base_prompt = base_prompt(session)
    opts = build_opts(session, base_prompt)

    Skill.assemble(skills, opts)
  end

  defp build_skills(%Session{agent: agent_module, actor: actor}) do
    agent_module
    |> AgentInfo.scoped_resources()
    |> Enum.map(fn resource ->
      skill_mod = AshHarness.ToolGen.skill_module(agent_module, resource)
      apply(skill_mod, :skill, [[actor: actor]])
    end)
  end

  defp base_prompt(%Session{rendered_context: nil}), do: ""
  defp base_prompt(%Session{rendered_context: %{initial_text: text}}), do: text

  defp build_opts(%Session{model: model} = session, base_prompt) do
    opts = [base_prompt: base_prompt]
    opts = if model, do: Keyword.put(opts, :model, model), else: opts
    opts ++ extra_opts(session)
  end

  defp extra_opts(%Session{options: options}) do
    Keyword.take(
      options || [],
      [:temperature, :max_tokens, :max_iterations, :req_options]
    )
  end

  defp maybe_put(opts, _key, nil), do: opts
  defp maybe_put(opts, key, value), do: Keyword.put(opts, key, value)
end
